# Generated by Django 5.2.8 on 2025-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_detail_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
